name: Android CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug
        run: ./gradlew clean :app:assembleDebug

      - name: Build Release
        run: ./gradlew :app:assembleRelease

      - name: Zip build trees (optional)
        run: |
          cd app/build
          mkdir -p ../outputs-zip
          zip -r ../outputs-zip/outputs-tree.zip outputs || true
          zip -r ../outputs-zip/reports-tree.zip reports || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apk-artifacts
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/apk/release/*.apk

      - name: Upload zipped logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-trees
          path: android/app/build/outputs-zip/*.zip