on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: "PR number to review (for manual runs)"
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Bluelibre_Aihelper
        uses: AirysDark/Bluelibre_AiHelper@95a0a02e7a566ea85c2b8980285634d2bcb6997e
        with:
          github_token: ${{ github.token }}
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}
        env:
          PR_NUMBER: ${{ inputs.pr_number }}   # <- used only for workflow_dispatch
